name: Sync Markdown to Confluence with Spell Check

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**/*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Spell check Markdown files
      uses: rojopolis/spellcheck-github-actions@0.33.1
      with:
        config_path: .github/spellcheck.yml
        source_files: 'docs/**/*.md'

    - name: Publish to Confluence using mark
      env:
        CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/docs:/data \
          -e CONFLUENCE_BASE_URL=$CONFLUENCE_BASE_URL \
          -e CONFLUENCE_USERNAME=$CONFLUENCE_USERNAME \
          -e CONFLUENCE_API_TOKEN=$CONFLUENCE_API_TOKEN \
          kovetskiy/mark:latest
