name: Sync Docs to Confluence

on:
  push:
    branches: [master]

jobs:
  sync-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
      CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
      CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
      CONFLUENCE_SPACE: demo
      CONFLUENCE_PARENT_ID: 284813

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Deploy Docs
          run: |
            for file in ${find docs/ -type f -name '*.md'); do}
                if [ -s "$file" ]; then
                    echo "> sync $file"
                    mark -u $CONFLUENCE_USER -p $CONFLUENCE_TOKEN -b $CONFLUENCE_BASE_URL -f $file --title-from-h1 --ci;
                else
                    echo "File is empty"
                fi
                echo;
            done
    