name: Sync Docs to Confluence

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    #env:
    #  CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
    #  CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
    #  CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
    #  CONFLUENCE_SPACE: demo
    #  CONFLUENCE_PARENT_ID: 284813  # Change to actual parent page ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker pull kovetskiy/mark:latest

      - name: Debug Mark Command
        run: |
            docker run --rm kovetskiy/mark:latest mark --version
            docker run --rm kovetskiy/mark:latest mark --help
        
      - name: Try a minimal valid Mark sync
        run: |
              docker run --rm \
                -v "${PWD}:/workspace" \
                -w /workspace \
                kovetskiy/mark:latest \
                mark \
                -u "${CONFLUENCE_USER}" \
                -p "${CONFLUENCE_TOKEN}" \
                -b "${CONFLUENCE_BASE_URL}" \
                -f "docs/example.md" \
                -s "${CONFLUENCE_SPACE}" \
                -P "${CONFLUENCE_PARENT_ID}" \
                --title-from-h1 --ci
          
      
        
        
        